-- MySQL Script generated by MySQL Workbench
-- Fri Mar 15 11:16:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema smp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smp` DEFAULT CHARACTER SET utf8mb3 ;
USE `smp` ;

-- -----------------------------------------------------
-- Table `smp`.`Maquina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smp`.`Maquina` (
  `idMaquina` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `numSerie` VARCHAR(255) NOT NULL,
  `dataInstalacao` DATE NOT NULL,
  `fabricante` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NOT NULL,
  `setor` VARCHAR(255) NOT NULL,
  `habilitada` TINYINT(1) NULL DEFAULT 1,
  `condicao` TINYINT(1) NULL DEFAULT 0,
  `estado` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idMaquina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `smp`.`SensorUmid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smp`.`SensorUmid` (
  `idSensor` VARCHAR(255) NOT NULL,
  `numSerie` VARCHAR(255) NOT NULL,
  `fabricante` VARCHAR(255) NOT NULL,
  `coordenadaX` INT NULL,
  `coodernadaY` INT NULL,
  `maxUmid` FLOAT NOT NULL,
  `minUmid` FLOAT NOT NULL,
  `idMaquina` VARCHAR(255) NOT NULL,
  `habilitada` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idSensor`, `idMaquina`),
  INDEX `fk_SensorUmid_Maquina1_idx` (`idMaquina` ASC) VISIBLE,
  CONSTRAINT `fk_SensorUmid_Maquina1`
    FOREIGN KEY (`idMaquina`)
    REFERENCES `smp`.`Maquina` (`idMaquina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`UmidColetada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smp`.`UmidColetada` (
  `valor` FLOAT NOT NULL,
  `dataColeta` DATE NOT NULL,
  `horaColeta` TIME NOT NULL,
  `idSensor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idSensor`, `dataColeta`, `horaColeta`),
  CONSTRAINT `fk_UmidColetada_SensorUmid1`
    FOREIGN KEY (`idSensor`)
    REFERENCES `smp`.`SensorUmid` (`idSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `smp`.`SensorTemp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smp`.`SensorTemp` (
  `idSensor` VARCHAR(255) NOT NULL,
  `numSerie` VARCHAR(255) NOT NULL,
  `fabricante` VARCHAR(255) NOT NULL,
  `coordenadaX` INT NULL,
  `coodernadaY` INT NULL,
  `maxTemp` FLOAT NOT NULL,
  `minTemp` FLOAT NOT NULL,
  `idMaquina` VARCHAR(255) NOT NULL,
  `habilitada` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idSensor`, `idMaquina`),
  INDEX `fk_SensorTemp_Maquina1_idx` (`idMaquina` ASC) VISIBLE,
  CONSTRAINT `fk_SensorTemp_Maquina1`
    FOREIGN KEY (`idMaquina`)
    REFERENCES `smp`.`Maquina` (`idMaquina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`TempColetada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smp`.`TempColetada` (
  `valor` FLOAT NOT NULL,
  `dataColeta` DATE NOT NULL,
  `horaColeta` TIME NOT NULL,
  `idSensor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idSensor`, `dataColeta`, `horaColeta`),
  CONSTRAINT `fk_TempColetada_SensorTemp1`
    FOREIGN KEY (`idSensor`)
    REFERENCES `smp`.`SensorTemp` (`idSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `smp` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
